Add missing jakarta.activation dependency
Fix java.lang.NoClassDefFoundError: jakarta/activation/DataSource in
unit test by adding missing runtime dependency to pom.xml.  Spring
Boot depends on javax.activation, but SADL actually depends on
jakarta.activation, not javax.activation, and so needs the additional
runtime dependency.

Also update dependencies and plugins in pom.xml to latest versions.